### ISSUE TITLE
Suggestion/Question: Are you interested in a semver/automatic-changelog-creation setup?

### ISSUE THREAD

**Issue by escapedcat** [alexbosworth/invoices#5]
How are realeses and versions created at the moment?
Noticed via [this depfu.com PR](https://github.com/getAlby/lightning-browser-extension/pull/787):

- 2.0.4 and 2.0.5 both are breaking changes. But both are released as patch-versions
- [2.0.4 is missing from the changelog](https://github.com/alexbosworth/invoices/blob/master/CHANGELOG.md) but [listed on npm](https://www.npmjs.com/package/invoices)

Suggestion:
- Write commit-messages according to https://www.conventionalcommits.org to create machine-readable commits
- Use https://github.com/semantic-release/semantic-release to create a new version/release based on commits
- Commits can be linted with https://commitlint.js.org if wanted

Could provide a PR for that.

**Comment by alexbosworth** [comment]
1.0 to 2.0 was intended as the breaking change

Is there a breaking change in the patches? Maybe I didn't notice

**Comment by alexbosworth** [comment]
Patch versions where there are no notable changes like dependency updates or issues with npm publishing don't get a line in the changelog

**Comment by escapedcat** [comment]
Thanks for your explanation, that clears things up.

Was confused by the depfu PR mentioning last changes:
![image](https://user-images.githubusercontent.com/1016218/162659478-74de399d-87db-4ee1-90e8-63ea419e6df2.png)

Then everything is how it should be.
Would be great if you could add [Github releases](https://github.com/alexbosworth/invoices/releases) as well. Quite soem people look at these as a first info about releases.

**Comment by alexbosworth** [comment]
Potentially I could add release tags, I do that on https://github.com/alexbosworth/balanceofsatoshis it is just part of the package scripts

bitcoinjs invoices lib is already doing tags https://github.com/bitcoinjs/bolt11

For release notes I prefer to document things in the changelog file to allow for flexibility in git remotes, like if I move the repo away from github things wouldn't change that much
